#微服务配置
spring:
  application:
    name: school-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: school
        group: school-project
      config:
        namespace: school
        group: school-project
        file-extension: yaml
        refresh-enabled: true
  #        shared-configs:
  #          - data-id: logging-${spring.profiles.active}.yaml
  #            group: xuecheng-plus-common
  #            refresh: true

  profiles:
    active: dev
server:
  port: 8000